export const articleActionTypes = {
   GET_ARTICLES_START: 'GET_ARTICLES_START',
   GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
   GET_ARTICLES_ERROR: 'GET_ARTICLES_ERROR',

   CREATE_ARTICLE_START: 'CREATE_ARTICLE_START',
   CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
   CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',

   GET_ARTICLE_START: 'GET_ARTICLE_START',
   GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS',
   GET_ARTICLE_ERROR: 'GET_ARTICLE_ERROR',

   UPDATE_ARTICLE_START: 'UPDATE_ARTICLE_START',
   UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
   UPDATE_ARTICLE_ERROR: 'UPDATE_ARTICLE_ERROR',

   DELETE_ARTICLE_START: 'DELETE_ARTICLE_START',
   DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
   DELETE_ARTICLE_ERROR: 'DELETE_ARTICLE_ERROR',
}