export const userActionTypes = {
   LOGIN_START: 'LOGIN_START',
   SET_LOGIN_SUCCESS_MESSAGE: 'SET_LOGIN_SUCCESS_MESSAGE',
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_ERROR: 'LOGIN_ERROR',

   SIGNUP_START: 'SIGNUP_START',
   SET_SIGNUP_SUCCESS_MESSAGE: 'SET_SIGNUP_SUCCESS_MESSAGE',
   SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
   SIGNUP_ERROR: 'SIGNUP_ERROR',

   LOGOUT_START: 'LOGOUT_START',
   LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
   LOGOUT_ERROR: 'LOGOUT_ERROR',

   FORGOTPASSWORD_START: 'FORGOTPASSWORD_START',
   SET_FORGOTPASSWORD_SUCCESS_MESSAGE: 'SET_FORGOTPASSWORD_SUCCESS_MESSAGE',
   FORGOTPASSWORD_ERROR: 'FORGOTPASSWORD_ERROR',

   RESETPASSWORD_START: 'RESETPASSWORD_START',
   SET_RESETPASSWORD_SUCCESS_MESSAGE: 'SET_RESETPASSWORD_SUCCESS_MESSAGE',
   RESETPASSWORD_ERROR: 'RESETPASSWORD_ERROR',

   UPDATEPASSWORD_START: 'UPDATEPASSWORD_START',
   SET_UPDATEPASSWORD_SUCCESS_MESSAGE: 'SET_UPDATEPASSWORD_SUCCESS_MESSAGE',
   UPDATEPASSWORD_ERROR: 'UPDATEPASSWORD_ERROR',

   UPDATE_USER: 'UPDATE_USER',

   DELETE_USER: 'DELETE_USER',
}