export const commentActionTypes = {

   CREATE_COMMENT_START: 'CREATE_COMMENT_START',
   CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
   CREATE_COMMENT_ERROR: 'CREATE_COMMENT_ERROR',

   GET_COMMENTS_START: 'GET_COMMENTS_START',
   GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
   GET_COMMENTS_ERROR: 'GET_COMMENTS_ERROR',

   UPDATE_COMMENT_START: 'UPDATE_COMMENT_START',
   UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
   UPDATE_COMMENT_ERROR: 'UPDATE_COMMENT_ERROR',

   DELETE_COMMENT_START: 'DELETE_COMMENT_START',
   DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
   DELETE_COMMENT_ERROR: 'DELETE_COMMENT_ERROR',
};